version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=ventas
      - POSTGRES_USER=lean
      - POSTGRES_PASSWORD=Lean123
    ports:
      - 5432:5432
    volumes:
      - './data:/var/lib/postgresql/data'